#cmakedefine LIBXML2_VERSION ${LIBXML2_VERSION_STRING}

#cmakedefine PGSQL_VERSION ${PostgreSQL_VERSION_STRING}

#cmakedefine POINTCLOUD_VERSION "${POINTCLOUD_VERSION_MAJOR}.${POINTCLOUD_VERSION_MINOR}.${POINTCLOUD_VERSION_PATCH}"

#cmakedefine HAVE_LIBGHT ${HAVE_LIBGHT}

#cmakedefine PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}"

#define LIBXML2_VERSION "@LIBXML2_VERSION_STRING@"
//#define PGSQL_VERSION @PostgreSQL_VERSION_STRING@
//#define PGSQL_VERSION @PGSQL_MAJOR_VERSION@@PGSQL_MINOR_VERSION@
#define PGSQL_VERSION 120

#define POINTCLOUD_VERSION "@POINTCLOUD_VERSION_MAJOR@.@POINTCLOUD_VERSION_MINOR@.@POINTCLOUD_VERSION_PATCH@"
